package aiss.dailymotionminer.etl;

import aiss.dailymotionminer.model.videominer.*;

public class Transformer {

    public static User transformUser(aiss.dailymotionminer.model.dailymotion.User dUser) {
        User vUser = new User();
        //Para preguntar: no puedo añadir el id porque en dailymotion es String (x23efgc)
        vUser.setName(dUser.getNickname());
        vUser.setUser_link(dUser.getUrl());
        vUser.setPicture_link(dUser.getAvatar60Url());
        return vUser;
    }

    public static Video transformVideo(aiss.dailymotionminer.model.dailymotion.Video dVideo) {
        Video vVideo = new Video();
        vVideo.setId(dVideo.getId());
        vVideo.setName(dVideo.getTitle());
        vVideo.setDescription(dVideo.getDescription());
        vVideo.setReleaseTime(dVideo.getUploadedTime().toString());
        return vVideo;
    }

    public static Channel transformChannel(aiss.dailymotionminer.model.dailymotion.Channel dChannel) {
        Channel vChannel = new Channel();
        vChannel.setId(dChannel.getId());
        vChannel.setName(dChannel.getNickname());
        vChannel.setDescription(dChannel.getDescription());
        vChannel.setCreatedTime(dChannel.getCreatedTime().toString());
        return vChannel;
    }

    public static Caption transformCaption(aiss.dailymotionminer.model.dailymotion.Subtitle dCaption) {
        Caption vCaption = new Caption();
        vCaption.setId(dCaption.getId());
        vCaption.setLanguage(dCaption.getLanguageLabel());
        vCaption.setName(dCaption.getUrl()); //Para preguntar: ¿cómo que name? No sale en el modelo de datos del PDF
        return vCaption;
    }

    public static Comment transformComment(String tagText) {
        Comment vComment = new Comment();
        vComment.setId(tagText); //No tiene @Autogenerated. Para evitar nulos, lo pongo así
        vComment.setText(tagText);
        vComment.setCreatedOn(java.time.LocalDate.now().toString());
        return vComment;
    }
}
