spring.application.name=dailymotionminer
server.port = 8081

logging.level.aiss.peertubeminer.controller=DEBUG
dailymotionminer.baseuri=https://api.dailymotion.com
dailymotionminer.maxVideos = 10
dailymotionminer.maxPages = 10

videominer.uri=http://localhost:8080/videominer/channels